title: Xueting Yang's Homepage
page-top-title: Xueting Yang
top-section-bg-text: Experimental Economics
home-subtitle: Xueting Yang&ensp;|&ensp;杨雪婷
copyright-text: '&copy; Sen Li 2023-2024. All Rights Reserved.'
